### ISSUE TITLE
Error inflating class ir.hamsaa.persiandatepicker.PersianDatePicker

### ISSUE THREAD

**Issue by fatemehmoradi110** [aliab/Persian-Date-Picker-Dialog#110]
Caused by: android.view.InflateException: Binary XML file line #27 in com.lablab:layout/dialog_picker: Error inflating class ir.hamsaa.persiandatepicker.PersianDatePicker
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
                                                                                                    	at android.view.View.inflate(View.java:29161)
                                                                                                    	at ir.hamsaa.persiandatepicker.PersianDatePickerDialog.show(PersianDatePickerDialog.java:271)
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker._init_$lambda$1(DatePicker.kt:97)
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker.$r8$lambda$7GtlYW5nIYkXYgCKptQvSIzgnNY(Unknown Source:0)
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7892)
                                                                                                    	at android.view.View.performClickInternal(View.java:7869)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30880)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.ClassCastException: android.widget.NumberPicker cannot be cast to ir.hamsaa.persiandatepicker.view.PersianNumberPicker
                                                                                                    	at ir.hamsaa.persiandatepicker.PersianDatePicker.<init>(PersianDatePicker.java:68)
                                                                                                    	at ir.hamsaa.persiandatepicker.PersianDatePicker.<init>(PersianDatePicker.java:58)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:876) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983) 
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145) 
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:692) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:544) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:491) 
                                                                                                    	at android.view.View.inflate(View.java:29161) 
                                                                                                    	at ir.hamsaa.persiandatepicker.PersianDatePickerDialog.show(PersianDatePickerDialog.java:271) 
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker._init_$lambda$1(DatePicker.kt:97) 
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker.$r8$lambda$7GtlYW5nIYkXYgCKptQvSIzgnNY(Unknown Source:0) 
                                                                                                    	at ir.isc.bankid.sdk.implementation.DatePicker$$ExternalSyntheticLambda0.onClick(Unknown Source:2) 
                                                                                                    	at android.view.View.performClick(View.java:7892) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7869) 
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:30880) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by fatemehmoradi110** [comment]
حل شد. کلاسی با همین نام در پروژه داشتیم
