### ISSUE TITLE
خطای FATAL EXCEPTION: main java.lang.NullPointerException

### ISSUE THREAD

**Issue by milimilad** [aliab/Persian-Date-Picker-Dialog#17]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NullPointerException
                                                                       at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:689)
                                                                       at java.util.Calendar.complete(Calendar.java:839)
                                                                       at java.util.Calendar.get(Calendar.java:901)
                                                                       at ir.hamsaa.persiandatepicker.util.PersianCalendar.calculatePersianDate(PersianCalendar.java:162)
                                                                       at ir.hamsaa.persiandatepicker.util.PersianCalendar.setTimeZone(PersianCalendar.java:380)
                                                                       at java.util.Calendar.<init>(Calendar.java:711)
                                                                       at java.util.Calendar.<init>(Calendar.java:723)
                                                                       at java.util.GregorianCalendar.<init>(GregorianCalendar.java:338)
                                                                       at ir.hamsaa.persiandatepicker.util.PersianCalendar.<init>(PersianCalendar.java:154)
                                                                       at ir.hamsaa.persiandatepicker.PersianDatePickerDialog.show(PersianDatePickerDialog.java:120)
                                                                       at com.milimilad.panbe.OrderActivity.showMyDialog(OrderActivity.java:594)
                                                                       at com.milimilad.panbe.OrderActivity$12.onClick(OrderActivity.java:404)
                                                                       at android.view.View.performClick(View.java:4084)
                                                                       at android.view.View$PerformClick.run(View.java:16966)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

سلام مشکل چیه؟ اندروید 5 به پایین کرش میشه برنامه! این از کدهامه:
```
persianDatePickerDialog = new PersianDatePickerDialog(OrderActivity.this)
                    .setPositiveButtonString("تایید")
                    .setNegativeButton("لفو")
                    .setTodayButton("برو به امروز")
                    .setTodayButtonVisible(true)
                    .setMaxYear(1450)
                    .setMinYear(persianDate.getShYear())
                    .setActionTextColor(getResources().getColor(R.color.textSecondary))
                    .setListener(new Listener() {
                        @Override
                        public void onDateSelected(PersianCalendar persianCalendar) {
                                    editText.setText(persianCalendar.getPersianYear() + "/" + persianCalendar.getPersianMonth() + "/" + persianCalendar.getPersianDay());
                        }

                        @Override
                        public void onDismissed() {
                        }
                    });
            persianDatePickerDialog.show();
```

خط persianDatePickerDialog.show(); رو ارور میگیره

**Comment by aliab** [comment]
با اندروید ۴.۲ تست کردم و مشکلی مشاهده نشد٬ شاید مشکل از کلاسی هست که سال حداقل رو باهاش تنظیم میکنید

**Comment by milimilad** [comment]
سلام اره تست کردم اندروید 4.2 کار میکنه! ولی تو ای پی آی 16 یا 15 این مشکل هستش هنوز

**Comment by aliab** [comment]
تست میکنم٬ البته اندروید پایین تر از 4.2 خیلی قدیمی به حساب میاد
