### ISSUE TITLE
Add Persian Date Error

### ISSUE THREAD

**Issue by am3n** [aliab/Persian-Date-Picker-Dialog#63]
hi, I am having an error when run the below code
```kt
val date = PersianCalendar().apply { 
    addPersianDate(Calendar.MONTH, -12)
}.persianDate()
```

```
Exception in thread "main" java.lang.IllegalArgumentException
	at ir.hamsaa.persiandatepicker.util.PersianCalendar.persianToGregorian(PersianCalendar.java:444)
	at ir.hamsaa.persiandatepicker.util.PersianCalendar.setPersianDate(PersianCalendar.java:192)
	at ir.hamsaa.persiandatepicker.util.PersianCalendar.addPersianDate(PersianCalendar.java:314)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.generated_get_instance_res0(tmp.kt:12)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.main(tmp.kt:20)
```

**Comment by aliab** [comment]
PersianCalendar class is now deprecated in the 1.6.1 version. check new version and migrate your code to the latest one and check if your issue is resolved or not.

**Comment by am3n** [comment]
Issue is not resolved and PersianCalendar class deprecated without any explanation or reason!
I used this library as persian calendar & persian date picker and just mentioned above that there is a problem when going back in time. 
if you want, maybe I can check it myself :)
